### ISSUE TITLE
ActivityStreams context URL doesn't resolve to JSON-LD

### ISSUE THREAD

**Issue by DePasqualeOrg** [digitalbazaar/jsonld-signatures#160]
I'm trying to sign an ActivityStreams document, but it only works if I add `.jsonld` to the `@context` URL (`https://www.w3.org/ns/activitystreams.jsonld`). Is this intended behavior, or should the library automatically resolve to the JSON-LD document based on the URL `https://www.w3.org/ns/activitystreams`?

**Comment by DePasqualeOrg** [comment]
According to [this](https://socialhub.activitypub.rocks/t/activitystreams-context-document/2267/3), it looks like this behavior is a bug, and the library should resolve to the JSON-LD document from `https://www.w3.org/ns/activitystreams`.

**Comment by DePasqualeOrg** [comment]
[This](https://socialhub.activitypub.rocks/t/activitystreams-context-document/2267/13?u=depasquale) looks like a potential solution to the problem. Could it be that the library is not using the `Accept: application/ld+json` header when accessing the `@context` URI?

**Comment by dmitrizagidulin** [comment]
Hi @DePasqualeOrg - can you share what the error is? 
I'm fairly sure that the jsonld.js library that jsonld-signatures is using is strict about including an `Accept: application/ld+json` header.

**Comment by DePasqualeOrg** [comment]
This is the error I get when using the `@context` URI without `.jsonld`:

```
/<redacted>/node_modules/jsonld/lib/ContextResolver.js:173
      throw new JsonLdError(
            ^

jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
    at ContextResolver._fetchContext (/<redacted>/node_modules/jsonld/lib/ContextResolver.js:173:13)
    at async ContextResolver._resolveRemoteContext (/<redacted>/node_modules/jsonld/lib/ContextResolver.js:117:34)
    at async ContextResolver.resolve (/<redacted>/node_modules/jsonld/lib/ContextResolver.js:50:22)
    at async api.process (/<redacted>/node_modules/jsonld/lib/context.js:65:20)
    at async api.expand (/<redacted>/node_modules/jsonld/lib/expand.js:211:17)
    at async Function.jsonld.expand (/<redacted>/node_modules/jsonld/lib/jsonld.js:325:18)
    at async Function.jsonld.toRDF (/<redacted>/node_modules/jsonld/lib/jsonld.js:671:16)
    at async Function.jsonld.normalize.jsonld.canonize (/<redacted>/node_modules/jsonld/lib/jsonld.js:580:19)
    at async Promise.all (index 1)
    at async Ed25519Signature2020.createVerifyData (/<redacted>/node_modules/jsonld-signatures/lib/suites/LinkedDataSignature.js:246:34) {
  details: {
    code: 'loading remote context failed',
    url: 'https://www.w3.org/ns/activitystreams',
    cause: Error: Document not found in document loader: https://www.w3.org/ns/activitystreams
        at JsonLdDocumentLoader.documentLoader (/<redacted>/node_modules/jsonld-document-loader/lib/JsonLdDocumentLoader.js:76:11)
        at /<redacted>/node_modules/jsonld-signatures/lib/documentLoader.js:48:12
        at ContextResolver._fetchContext (/<redacted>/node_modules/jsonld/lib/ContextResolver.js:166:25)
        at ContextResolver._resolveRemoteContext (/<redacted>/node_modules/jsonld/lib/ContextResolver.js:117:45)
        at ContextResolver.resolve (/<redacted>/node_modules/jsonld/lib/ContextResolver.js:50:33)
        at api.process (/<redacted>/node_modules/jsonld/lib/context.js:65:50)
        at api.expand (/<redacted>/node_modules/jsonld/lib/expand.js:211:23)
        at Function.jsonld.expand (/<redacted>/node_modules/jsonld/lib/jsonld.js:325:24)
        at Function.jsonld.toRDF (/<redacted>/node_modules/jsonld/lib/jsonld.js:671:29)
        at Function.jsonld.normalize.jsonld.canonize (/<redacted>/node_modules/jsonld/lib/jsonld.js:580:32)
  }
}
```

**Comment by dlongley** [comment]
I haven't been following this very closely, but if this hasn't been said yet, jsonld-signatures is a security library so, by default, it fails closed. It has a built-in document loader that *only* loads the security v2 context that has some security terms in it.

You MUST pass your own document loader to its API to load any other contexts you wish to load, for example, the activity streams context. The preferred and most secure mechanism for this is to provide a document loader that loads static copies of contexts from disk / memory, but the library will work if you pass it a document loader that loads remote documents.

This behavior is also documented in the README for this library here:

https://github.com/digitalbazaar/jsonld-signatures#document-loader

I'm swamped with work and can't be of much more assistance here now, but there is a custom static document loader example here: https://github.com/digitalbazaar/jsonld.js/#custom-document-loader

I'm sure that example could be improved in a number of ways, but it does demonstrate the basic idea. It also shows that it falls back to the default node.js remote document loader (which isn't a best security practice but should help get you unstuck if this is indeed the problem here).

**Comment by dlongley** [comment]
Another way of putting my comments above is: This library doesn't do any remote document loading, so the problem must be elsewhere in the stack or in what is or isn't being passed to its API.

**Comment by DePasqualeOrg** [comment]
Yes, I'm already using the document loader this way. The problem is with the `@context` URL in the JSON-LD document to be signed. I get the above error when the document contains the URL `https://www.w3.org/ns/activitystreams` in the `@context` field (as it should), and no error when adding `.jsonld` to that URL, which as I understand is not the correct usage of the spec. I can post a full code example later when I'm able to clean everything up for clarity, but I think it should be clear from this description what I mean.

**Comment by DePasqualeOrg** [comment]
[Here](https://gist.github.com/DePasqualeOrg/c12f34720cf27dc31183c938ac1e1c0d) is a full working code example that demonstrates this behavior.

**Comment by dlongley** [comment]
The code there adds the activity streams context as a static context using this key:

`'https://www.w3.org/ns/activitystreams.jsonld'`
https://gist.github.com/DePasqualeOrg/c12f34720cf27dc31183c938ac1e1c0d#file-main-js-L13

Just change that to remove `.jsonld` and then when the doc loader looks for `'https://www.w3.org/ns/activitystreams'` it should find the static context you registered.

**Comment by DePasqualeOrg** [comment]
Fantastic, thanks! I've updated the gist to demonstrate what I think is the correct usage. Feel free to add this to your code examples if you like. Maybe that will help more people like me get started in this space.
