### ISSUE TITLE
Dependency `jsonld` 0.4.4+ causes tests to fail

### ISSUE THREAD

**Issue by harlantwood** [digitalbazaar/jsonld-signatures#7]
0.4.3 works fine

**Comment by harlantwood** [comment]
This is pretty bad.  When I use the latest jsonld lib, 1.4.7, we fail on CI in node 0.10 and 0.12.

Weirdly, on my local mac, in node 6, the failures are worse:

```
Running "mochaTest:test" (mochaTest) task


  JSON-LD Signatures
    signing and verify Graph2012 w/o security context
      ✓ should successfully sign a local document (997ms)
      1) should successfully verify a local signed document
      ✓ should successfully sign a local document w/promises API (224ms)
      2) should successfully verify a local signed document w/promises API
    signing and verify Graph2015 w/o security context
      ✓ should successfully sign a local document (475ms)
      3) should successfully verify a local signed document
      ✓ should successfully sign a local document w/promises API (390ms)
      4) should successfully verify a local signed document w/promises API
    signing and verify BitcoinSignature2016 w/o security context
      ✓ should successfully sign a local document (599ms)
      5) should successfully verify a local signed document
      6) verify should return false if the document was signed by a different private key
      - should successfully sign a local document w/promises API
      - should successfully verify a local signed document w/promises API
    signing and verify GraphSignature2012 w/security context
      ✓ should successfully sign a local document (1850ms)
      7) should successfully sign a local document
      signing and verify LinkedDataSignature2015 w/security context
        ✓ should successfully sign a local document (1850ms)
        ✓ should successfully sign a local document (1849ms)
        8) should successfully verify a local signed document
        ✓ should successfully sign a local document w/promises (1697ms)
        9) should successfully verify a local signed document w/promises


  9 passing (24s)
  2 pending
  9 failing

  1) JSON-LD Signatures signing and verify Graph2012 w/o security context should successfully verify a local signed document:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) JSON-LD Signatures signing and verify Graph2012 w/o security context should successfully verify a local signed document w/promises API:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  3) JSON-LD Signatures signing and verify Graph2015 w/o security context should successfully verify a local signed document:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  4) JSON-LD Signatures signing and verify Graph2015 w/o security context should successfully verify a local signed document w/promises API:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  5) JSON-LD Signatures signing and verify BitcoinSignature2016 w/o security context should successfully verify a local signed document:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  6) JSON-LD Signatures signing and verify BitcoinSignature2016 w/o security context verify should return false if the document was signed by a different private key:

      Uncaught AssertionError: signature verification failed
      + expected - actual

      -false
      +true
      
      at tests/test.js:334:16
      at lib/jsonld-signatures.js:663:5
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:550:17
      at node_modules/async/lib/async.js:544:17
      at _arrayEach (node_modules/async/lib/async.js:85:13)
      at Immediate.taskComplete (node_modules/async/lib/async.js:543:13)

  7) JSON-LD Signatures signing and verify GraphSignature2012 w/security context should successfully sign a local document:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at tests/test.js:349:9
      at lib/jsonld-signatures.js:663:5
      at node_modules/async/lib/async.js:52:16
      at node_modules/async/lib/async.js:550:17
      at node_modules/async/lib/async.js:544:17
      at _arrayEach (node_modules/async/lib/async.js:85:13)
      at Immediate.taskComplete (node_modules/async/lib/async.js:543:13)

  8) JSON-LD Signatures signing and verify LinkedDataSignature2015 w/security context should successfully verify a local signed document:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  

  9) JSON-LD Signatures signing and verify LinkedDataSignature2015 w/security context should successfully verify a local signed document w/promises:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by dlongley** [comment]
Interesting, very slow for me here as well -- seems `setImmediate`/`Promise` related?

**Comment by dlongley** [comment]
So the difference between jsonld 0.4.3 and jsonld 0.4.4 was disabling the document cache. So we may be getting rate limited on fetching something we need for the tests.

**Comment by dlongley** [comment]
Yup, that's it. Just tested with jsonld 0.4.7 by re-enabling the document cache and it's fast and passes again. The fix for this is to use a local document loader that will pull in whatever the tests need from a local static copy instead of pulling from the net (which I would have thought we were doing previously, but I guess not).

**Comment by dlongley** [comment]
Oops, wrong button :)

**Comment by harlantwood** [comment]
Agreed.  I wasn't sure how to correctly fix the external calls in the tests, so I put a 1 sec pause before each test and they all passed:  https://github.com/CoMakery/jsonld-signatures/commit/3f86b074c2231642b40ccc4d2d9a66b5280d7113.

**Comment by dlongley** [comment]
New test suite written -- all files loaded locally.
